/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLy;

import java.awt.Color;
import org.w3c.dom.css.RGBColor;

/**
 *
 * @author Anh Kiet
 */
public class QuanLyVatTu extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyVatTu
     */
    public QuanLyVatTu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtn_NhanVien = new javax.swing.JButton();
        jbtn_VatTu = new javax.swing.JButton();
        jbtnHoaDon = new javax.swing.JButton();
        jbtn_CTHD = new javax.swing.JButton();
        jbtn_ThongKe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 23, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jbtn_NhanVien.setBackground(new java.awt.Color(51, 0, 102));
        jbtn_NhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_NhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_NhanVien.setText("NHÂN VIÊN\n");
        jbtn_NhanVien.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jbtn_NhanVienMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtn_NhanVienMouseMoved(evt);
            }
        });
        jbtn_NhanVien.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jbtn_NhanVienMouseWheelMoved(evt);
            }
        });
        jbtn_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbtn_NhanVienMouseReleased(evt);
            }
        });
        jbtn_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_NhanVienActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 160, 210, 70));

        jbtn_VatTu.setBackground(new java.awt.Color(51, 0, 102));
        jbtn_VatTu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_VatTu.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_VatTu.setText("VẬT TƯ\n");
        jbtn_VatTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_VatTuActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_VatTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 230, 210, 70));

        jbtnHoaDon.setBackground(new java.awt.Color(51, 0, 102));
        jbtnHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jbtnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bill48.png"))); // NOI18N
        jbtnHoaDon.setText("HÓA ĐƠN\n");
        jbtnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnHoaDonMouseExited(evt);
            }
        });
        jbtnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHoaDonActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 300, 210, 71));

        jbtn_CTHD.setBackground(new java.awt.Color(51, 0, 102));
        jbtn_CTHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_CTHD.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_CTHD.setText("CHI TIẾT HÓA ĐƠN\n");
        jbtn_CTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CTHDActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_CTHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 370, 210, 70));

        jbtn_ThongKe.setBackground(new java.awt.Color(51, 0, 102));
        jbtn_ThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_ThongKe.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_ThongKe.setText("THỐNG KÊ\n");
        jPanel1.add(jbtn_ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 440, 210, 71));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user80.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, -1));

        jButton1.setText("Đăng xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 561));
        getContentPane().add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, -35, -1, 590));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(583, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel5);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel10);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 920, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_NhanVienActionPerformed
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_jbtn_NhanVienActionPerformed

    private void jbtn_VatTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_VatTuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_VatTuActionPerformed

    private void jbtnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnHoaDonActionPerformed

    private void jbtn_CTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CTHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_CTHDActionPerformed

    private void jbtn_NhanVienMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_NhanVienMouseDragged
        
    }//GEN-LAST:event_jbtn_NhanVienMouseDragged

    private void jbtn_NhanVienMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_NhanVienMouseMoved
        
    }//GEN-LAST:event_jbtn_NhanVienMouseMoved

    private void jbtn_NhanVienMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jbtn_NhanVienMouseWheelMoved
       
    }//GEN-LAST:event_jbtn_NhanVienMouseWheelMoved

    private void jbtn_NhanVienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_NhanVienMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jbtn_NhanVienMouseReleased

    private void jbtnHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnHoaDonMouseEntered
        jbtnHoaDon.setBackground(new Color(0,255,255));
    }//GEN-LAST:event_jbtnHoaDonMouseEntered

    private void jbtnHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnHoaDonMouseExited
        jbtnHoaDon.setBackground(new Color(51, 0, 102));
    }//GEN-LAST:event_jbtnHoaDonMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyVatTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyVatTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyVatTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyVatTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyVatTu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnHoaDon;
    private javax.swing.JButton jbtn_CTHD;
    private javax.swing.JButton jbtn_NhanVien;
    private javax.swing.JButton jbtn_ThongKe;
    private javax.swing.JButton jbtn_VatTu;
    // End of variables declaration//GEN-END:variables

    private Color RGBColor(int i, int i0, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
