/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLy;

import java.awt.Color;

/**
 *
 * @author Anh Kiet
 */
public class QuanLyVatTu extends javax.swing.JFrame {

    
    public QuanLyVatTu() {
        initComponents();
        setLocationRelativeTo(null);
        Panel_NhanVien panel_NhanVien = new Panel_NhanVien();
        jTabbedPane2.add("tab2",panel_NhanVien);
        Panel_VatTu panel_VatTu = new Panel_VatTu();
        jTabbedPane2.add("tab3",panel_VatTu);
        Panel_NhaCungCap panel_NhaCungCap = new Panel_NhaCungCap();
        jTabbedPane2.add("tab4",panel_NhaCungCap);
        Panel_HoaDon panel_HoaDon = new Panel_HoaDon();
        jTabbedPane2.add("tab5",panel_HoaDon);
        Panel_CTHoaDon panel_CTHoaDon = new Panel_CTHoaDon();
        jTabbedPane2.add("tab6",panel_CTHoaDon);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtn_NhanVien = new javax.swing.JButton();
        jbtn_VatTu = new javax.swing.JButton();
        jbtnHoaDon = new javax.swing.JButton();
        jbtn_NhaCungCap = new javax.swing.JButton();
        jbtn_ThongKe = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_username = new javax.swing.JLabel();
        role1 = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 23, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jbtn_NhanVien.setBackground(new java.awt.Color(51, 0, 102));
        jbtn_NhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_NhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_NhanVien.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Downloads\\employees48.png")); // NOI18N
        jbtn_NhanVien.setText("NHÂN VIÊN\n");
        jbtn_NhanVien.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jbtn_NhanVienMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtn_NhanVienMouseMoved(evt);
            }
        });
        jbtn_NhanVien.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jbtn_NhanVienMouseWheelMoved(evt);
            }
        });
        jbtn_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_NhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtn_NhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtn_NhanVienMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbtn_NhanVienMouseReleased(evt);
            }
        });
        jbtn_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_NhanVienActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 160, 210, 70));

        jbtn_VatTu.setBackground(new java.awt.Color(51, 0, 102));
        jbtn_VatTu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_VatTu.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_VatTu.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Downloads\\stationery48.png")); // NOI18N
        jbtn_VatTu.setText("VẬT TƯ\n");
        jbtn_VatTu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_VatTuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtn_VatTuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtn_VatTuMouseExited(evt);
            }
        });
        jbtn_VatTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_VatTuActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_VatTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 230, 210, 70));

        jbtnHoaDon.setBackground(new java.awt.Color(51, 0, 102));
        jbtnHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jbtnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bill48.png"))); // NOI18N
        jbtnHoaDon.setText("HÓA ĐƠN\n");
        jbtnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnHoaDonMouseExited(evt);
            }
        });
        jbtnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHoaDonActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 300, 210, 71));

        jbtn_NhaCungCap.setBackground(new java.awt.Color(51, 0, 102));
        jbtn_NhaCungCap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_NhaCungCap.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_NhaCungCap.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Downloads\\supplier48.png")); // NOI18N
        jbtn_NhaCungCap.setText("NHÀ CUNG CẤP\n\n");
        jbtn_NhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_NhaCungCapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtn_NhaCungCapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtn_NhaCungCapMouseExited(evt);
            }
        });
        jbtn_NhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_NhaCungCapActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_NhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 370, 210, 70));

        jbtn_ThongKe.setBackground(new java.awt.Color(51, 0, 102));
        jbtn_ThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn_ThongKe.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_ThongKe.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Downloads\\bar-graph48.png")); // NOI18N
        jbtn_ThongKe.setText("THỐNG KÊ\n");
        jbtn_ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_ThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtn_ThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtn_ThongKeMouseExited(evt);
            }
        });
        jPanel1.add(jbtn_ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 440, 210, 71));

        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user80.png"))); // NOI18N
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, 90));

        txt_MaNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_MaNV.setForeground(new java.awt.Color(255, 255, 255));
        txt_MaNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_MaNV.setText("NV001");
        jPanel1.add(txt_MaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, -1));

        jButton1.setText("Đăng xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 100, 40));

        txt_username.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_username.setText("username");
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 120, -1));

        role1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        role1.setForeground(new java.awt.Color(255, 255, 255));
        role1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        role1.setText("role");
        jPanel1.add(role1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 720));
        getContentPane().add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, -35, -1, 590));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel3);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -20, 1240, 720));
        getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_NhanVienActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbtn_NhanVienActionPerformed

    private void jbtn_VatTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_VatTuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_VatTuActionPerformed

    private void jbtnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnHoaDonActionPerformed

    private void jbtn_NhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_NhaCungCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_NhaCungCapActionPerformed

    private void jbtn_NhanVienMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_NhanVienMouseDragged
        
    }//GEN-LAST:event_jbtn_NhanVienMouseDragged

    private void jbtn_NhanVienMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_NhanVienMouseMoved
        
    }//GEN-LAST:event_jbtn_NhanVienMouseMoved

    private void jbtn_NhanVienMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jbtn_NhanVienMouseWheelMoved
       
    }//GEN-LAST:event_jbtn_NhanVienMouseWheelMoved

    private void jbtn_NhanVienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_NhanVienMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jbtn_NhanVienMouseReleased

    private void jbtnHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnHoaDonMouseEntered
        jbtnHoaDon.setBackground(new Color(0,255,255));
       
    }//GEN-LAST:event_jbtnHoaDonMouseEntered

    private void jbtnHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnHoaDonMouseExited
        jbtnHoaDon.setBackground(new Color(51, 0, 102));
    }//GEN-LAST:event_jbtnHoaDonMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnHoaDonMouseClicked
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(4);
    }//GEN-LAST:event_jbtnHoaDonMouseClicked

    private void jbtn_ThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_ThongKeMouseEntered
        jbtn_ThongKe.setBackground(new Color(0,255,255));
        
    }//GEN-LAST:event_jbtn_ThongKeMouseEntered

    private void jbtn_ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_ThongKeMouseClicked
         jTabbedPane2.setSelectedIndex(5);
    }//GEN-LAST:event_jbtn_ThongKeMouseClicked

    private void jbtn_ThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_ThongKeMouseExited
        jbtn_ThongKe.setBackground(new Color(51, 0, 102));
    }//GEN-LAST:event_jbtn_ThongKeMouseExited

    private void jbtn_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_NhanVienMouseClicked

         jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_jbtn_NhanVienMouseClicked

    private void jbtn_NhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_NhanVienMouseEntered
        jbtn_NhanVien.setBackground(new Color(0,255,255));
        
    }//GEN-LAST:event_jbtn_NhanVienMouseEntered

    private void jbtn_NhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_NhanVienMouseExited

        jbtn_NhanVien.setBackground(new Color(51, 0, 102));
        
    }//GEN-LAST:event_jbtn_NhanVienMouseExited

    private void jbtn_VatTuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_VatTuMouseClicked
         jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_jbtn_VatTuMouseClicked

    private void jbtn_VatTuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_VatTuMouseEntered

         jbtn_VatTu.setBackground(new Color(0,255,255));
        
    }//GEN-LAST:event_jbtn_VatTuMouseEntered

    private void jbtn_VatTuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_VatTuMouseExited
        // TODO add your handling code here: jTabbedPane2.setSelectedIndex(3);
          jbtn_VatTu.setBackground(new Color(51, 0, 102));
        
    }//GEN-LAST:event_jbtn_VatTuMouseExited

    private void jbtn_NhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_NhaCungCapMouseClicked
        // TODO add your handling code here:
         jTabbedPane2.setSelectedIndex(3);
         
    }//GEN-LAST:event_jbtn_NhaCungCapMouseClicked

    private void jbtn_NhaCungCapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_NhaCungCapMouseEntered
        // TODO add your handling code here:
         jbtn_NhaCungCap.setBackground(new Color(0,255,255));
    }//GEN-LAST:event_jbtn_NhaCungCapMouseEntered

    private void jbtn_NhaCungCapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_NhaCungCapMouseExited
        // TODO add your handling code here:
          jbtn_NhaCungCap.setBackground(new Color(51, 0, 102));
    }//GEN-LAST:event_jbtn_NhaCungCapMouseExited





    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyVatTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyVatTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyVatTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyVatTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyVatTu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton jbtnHoaDon;
    private javax.swing.JButton jbtn_NhaCungCap;
    private javax.swing.JButton jbtn_NhanVien;
    private javax.swing.JButton jbtn_ThongKe;
    private javax.swing.JButton jbtn_VatTu;
    private javax.swing.JLabel role1;
    public javax.swing.JLabel txt_MaNV;
    public javax.swing.JLabel txt_username;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

    private Color RGBColor(int i, int i0, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
